
conntimeout=10000
readtimeout=30000

# Oracle settings
#Local Server
#spring.datasource.url=jdbc:oracle:thin:@10.32.47.XXXXX:1521:XXXXX
#spring.datasource.username=XXXXX
#spring.datasource.password=XXXXX
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#
#ds-token-url=https://stg-ds.sharjah.ae/appgateservices/api/api/login
#ds-ext-token-url=https://stg-ds.sharjah.ae/appgateservices/api/api/login-en
#ds-nty-token-url=https://stg-ds.sharjah.ae/securityservices/api/api/security/login-entity-v2
#
#ucm.admin.username=DSWCC
#ucm.admin.password=XXXXX
#ds-valid-user=DS_US_29621

#STG Env
# Oracle settings
#jndi
#spring.datasource.jndi-name=jdbc/DigitalSharjah
#
#ds-token-url=https://stg-ds.sharjah.ae/appgateservices/api/api/login
#ds-ext-token-url=https://stg-ds.sharjah.ae/appgateservices/api/api/login-en
#ds-nty-token-url=https://stg-ds.sharjah.ae/securityservices/api/api/security/login-entity-v2
#
#ucm.admin.username=DSWCC
#ucm.admin.password=XXXXX
#ds-valid-user=DS_US_29621


#PROD Env
#jndi
spring.datasource.jndi-name=jdbc/DigitalSharjah
ds-valid-user=DS_US_81389

ds-token-url=https://ds.sharjah.ae/appgateservices/api/api/login
ds-ext-token-url=https://ds.sharjah.ae/appgateservices/api/api/login-en
ds-nty-token-url=https://ds.sharjah.ae/securityservices/api/api/security/login-entity-v2
ucm.admin.username=DSWCC
ucm.admin.password=XXXXX